# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc5f9aeeecf3dcae3365f68d9eaf41f3436966b025db67b24df652c920205b12bd5c3437af78174511b602e4e084b043629b2a7c88ea232165f5e9d4dbaf122b

test:
  secret_key_base: 4db825f5944b47f71b6315bfc3640aaf5269cf58fb2a577047f98ff7d120eeb47003b6978cc0315f2660697e31a5dddbf4cc869371560815b97f586ee55a9e05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
